// build.rs exposes the resource directory generated by tauri-build. `-bundle`
// passes the resource directly to the linker instead of treating the .res data
// as an archive to embed in an rlib. This module is compiled only by lib tests;
// the application binary gets its resource from Tauri's rustc-link-arg-bins.
#[link(name = "resource", kind = "static", modifiers = "-bundle")]
extern "C" {}
